version: '3.8'

services:
  app:
    build: .
    container_name: taskmanager-app
    ports:
      - '3000:3000'
    env_file:
      - .env.example
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo:6.0
    container_name: taskmanager-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: taskmanager

volumes:
  mongo-data:
